### ISSUE TITLE
Добавить правила фильтрации донатных сообщений по словам-исключениям

### ISSUE THREAD

**Issue by lejafo** [catebi/FreeganBot#54]
по аналогии с тем как организован отбор сообщений по дополнительным вхождениям из фильтрующих слово-групп (из конфигурации) сделать возможность фильтрации через слова из групп исключений

например, фриган должен найти что-то из группы слов `кондиционер, кондей, сплит-система`, но при этом сообщения не должны содержать слов `аренда, купить, шампунь`

нужно:
- добавить в конфигурацию дополнительные группы для фильтрации по исключениям
- доработать логику отбора сообщений для учета исключающих слово-групп

текущая конфигурация 
```yaml
keyword_group_2:
  - 'витамин'
  - 'вкусняшка'
  - 'домик'
  - 'еда'
  - 'звенелка'
  - 'игрушка'
  - 'каталка'
  - 'клетка'
  - 'лакомство'
  - 'лекарство'
  - 'мята'
  - 'наполнитель'

keyword_group_3:
  - 'подушка'

keyword_group_4:
  - 'переноска'
  - 'миска'

filter_keyword_group_2:
  - животное
  - кошачий
  - кошка
  - кот

filter_keyword_group_3:
  - бесплатно
  - донат
  - плоская
  - лежанка
  - кошачий
  - кошка
  - кот

filter_keyword_group_4:
  - животное
  - кошачий
  - кошка
  - кот
  - собака
  - собачья
```

<img width="767" alt="image" src="https://github.com/catebi/FreeganBot/assets/7479125/1609281d-3246-414e-a87f-d735acc77e83">
