### ISSUE TITLE
Рефакторинг применения правил для конфигурации

### ISSUE THREAD

**Issue by lejafo** [catebi/FreeganBot#55]
цель: избавится от хардкодного варианта задания групп ключевых слов и фильтрующих групп (включательных/исключательных) и сделать динамическую конструкцию для обобщённого применения правил к заданным слово-группам

вместо текущего конфига должно быть нечто вроде такого:

```yaml
groups:
  - name: 'main group'
    keywords:
      - 'ампула'
      - 'бентонит'
      - 'бетонит'
      - 'верёвка'
      - 'вольер'    
      - 'шлейка'
      - 'шприц'
      ...
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 1'
    keywords:
      - 'витамин'
      - 'вкусняшка'
      - 'домик'
      - 'еда'
      - 'звенелка'
      - 'игрушка'
      - 'каталка'
      - 'клетка'
      - 'лакомство'
      - 'лекарство'
      - 'мята'
      - 'наполнитель'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 2'
    keywords:
      - 'подушка'
    include_keywords:
      - 'бесплатно'
      - 'донат'
      - 'плоская'
      - 'лежанка'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 3'
    keywords:
      - 'переноска'
      - 'миска'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
      - 'собака'
      - 'собачья'
  - name: 'air conditioner group' 
    keywords:
      - 'кондиционер'
      - 'кондей'
      - 'сплитсистема'
      - 'сплит-система'
    exclude_keywords:
      - 'аренда'
      - 'сдается'
      - 'трансфер'
      - 'шампунь'
```
